{{- if and .Values.enabled .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cert.serviceAccountName" . }}
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
  labels:
    {{- include "cert.labels" . | nindent 4 }}
{{- end -}}
